### Endpoint de teste
GET http://localhost:3003/ping


### Endpoint signup
POST http://localhost:3003/signup
Content-Type: application/json

{
  "nickname":"macedo",
  "email":"macedo@msn.com",
  "password":"lucas123"
}

### Endpoint login
POST http://localhost:3003/login
Content-Type: application/json

{
  "email":"macedo@msn.com",
  "password":"lucas123"
}

### Endpoint getallusers
GET http://localhost:3003/users?q=
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZmN2Q2NjhhLWM0NDctNGM5Mi04OTM4LTJlZTNkOTg1ZmQ1MyIsImlhdCI6MTY1OTM3Nzk5OSwiZXhwIjoxNjU5NDY0Mzk5fQ.s1HVqTsy3jknbXsxWXMvcKZKGC3P-kxFmoT3Tkr_A3Q

### Endpoint change data
PUT http://localhost:3003/users
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZmN2Q2NjhhLWM0NDctNGM5Mi04OTM4LTJlZTNkOTg1ZmQ1MyIsImlhdCI6MTY1OTM3Nzk5OSwiZXhwIjoxNjU5NDY0Mzk5fQ.s1HVqTsy3jknbXsxWXMvcKZKGC3P-kxFmoT3Tkr_A3Q
Content-Type: application/json

{
  "nickname":"",
  "email":"macedo@msn.com",
  "password":"lucas123"
}