### Endpoint de teste
GET http://localhost:3003/ping

### 1) Signup
POST http://localhost:3003/users/signup
Content-Type: application/json

{
    "name": "Beltrano",
    "email": "beltrano@gmail.com",
    "password": "abc123"
}

### 2) Login
POST http://localhost:3003/users/login
Content-Type: application/json

{
    "email": "astrodev@gmail.com",
    "password": "bananinha"
}

### 3) Get users
GET http://localhost:3003/users
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImE0YWYwOWM1LTcwZjktNGRhNC04YzFkLTM5YTBlN2VjNzkwMSIsInJvbGUiOiJOT1JNQUwiLCJpYXQiOjE2NTk5ODYwMzYsImV4cCI6MTY2MDA3MjQzNn0.obm0LBIn2cU3U23k2zsTnAcR59MH8KEE6KJ7S2R0Zz8

### 3) Delete user
DELETE http://localhost:3003/users/7079b8e4-95cd-48aa-82a9-77454e94b789
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImJiOWI3ZWU4LWFlNGItNGJkMS05YmQ2LWU3ZTIxNTk0Mzk5YiIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTY1OTk4ODcxMywiZXhwIjoxNjYwMDc1MTEzfQ.FdeMErg5GyXWr9IJuA99fyG2m3EJSJ5kCFKZKseaDIs