### Endpoint de teste
GET http://localhost:3003/ping


### get all students
GET http://localhost:3003/students

### creeate class

### Exercício 3 - Create product
POST http://localhost:3003/classroom
Content-Type: application/json

{
    "name": "bill gates",
    "students": ["lucas"],
    "module": "MODULO_5"
}
